### ISSUE TITLE
way to use MUCH less ram (your basic example goes from 1121 bytes to 77 bytes)

### ISSUE THREAD

**Issue by ortegafernando** [baghayi/Nokia_5110#1]
Hi, I have found your library. It is great as it is not depends on SPI pins.

But I have found a good way so save LOTS of RAM.

In Font.h file it would be great to declare characters array in FLASH MEMORY with PROGMEM. This includes to change the findCorrespondingByte function. Other functions could be left UNtouched.

But I am a newbie. Could you try do this for all community ?

Regards,

**Comment by baghayi** [comment]
Hi, 
I didn't know about the ability to store arrays in flash memory.
You're right. It would be better to have fonts stored in flash memory.
I will start working on them.

**Comment by ortegafernando** [comment]
Hi, I have already done it. Please, check pull request.

**Comment by baghayi** [comment]
Hi, Thanks for the pull-request, I really appreciate it.  It truly saved plenty of sram. :D 
I merged it into master. I will tag a new version and push it up for this.
