### ISSUE TITLE
Can't fit 14 characters on one line.

### ISSUE THREAD

**Issue by a1b0hph0b1a** [baghayi/Nokia_5110#4]
So, I like how your library actually works with the ESP8266 (unlike Adafruit's), however I've encountered some issues...

This particular issue is how you can't get 14 characters on one line. You should be able to, but you made a minor mistake in Nokia_5110.cpp. On line 98 the line says < 83 but should be < 85 as there are 84 pixels across the screen.

Just thought you might like to know and update the library.

**Comment by baghayi** [comment]
You're right. there could be one more pixel in there.
I made the changes and tagged it as 1.0.4.

Thank you for reporting the issue :)
